version: "3.8"
services:
  postgres:
    image: postgres:14.8
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - docker-network-dev

  timescale-ha:
    image: timescale/timescaledb-ha:pg15-latest
    container_name: timescale-ha
    restart: always
    environment:
      POSTGRES_USER: ${TIMESCALE_HA_USER}
      POSTGRES_PASSWORD: ${TIMESCALE_HA_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${TIMESCALE_HA_PORT}:5432"
    volumes:
      - ./db/timescale-ha:/home/postgres/pgdata/data
    networks:
      - docker-network-dev

  timescale:
    image: timescale/timescaledb:latest-pg16
    container_name: timescale
    restart: always
    environment:
      POSTGRES_USER: ${TIMESCALE_USER}
      POSTGRES_PASSWORD: ${TIMESCALE_PASSWORD}
    env_file:
      - .env
    ports:
      - "${TIMESCALE_PORT}:5432"
    volumes:
      - ./db/timescale:/var/lib/postgresql/data
    networks:
      - docker-network-dev

  mysql:
    image: mysql:8.0.31
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - docker-network-dev

  redis:
    image: redis:6.2.0
    container_name: redis
    restart: always
    volumes:
      - ./db/redis:/var/lib/redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_PORT_1}:16379"
    networks:
      - docker-network-dev

  mongodb:
    image: mongo:7.0.6
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_DATABASE_USERNAME: ${MONGO_DATABASE_USERNAME}
      MONGO_DATABASE_PASSWORD: ${MONGO_DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./db/mongodb:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d/:ro
    networks:
      - docker-network-dev

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    env_file:
      - .env
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_PORT_UI}:15672"
    volumes:
      - ./db/rabbitmq:/var/lib/rabbitmq/mnesia/
    networks:
      - docker-network-dev

  elasticsearch:
    image: bitnami/elasticsearch:8.5.3
    container_name: elasticsearch
    restart: always
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
      - "${ELASTICSEARCH_PORT_1}:9300"
    volumes:
      - ./db/elastic:/bitnami/elasticsearch/data
    networks:
      - docker-network-dev

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: kibana
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
    env_file:
      - .env
    ports:
      - "${kIBANA_PORT}:5601"
    networks:
      - docker-network-dev

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    env_file:
      - .env
    environment:
      KAFKA_KRAFT_MODE: ${KAFKA_KRAFT_MODE}
      KAFKA_PROCESS_ROLES: ${KAFKA_PROCESS_ROLES}
      KAFKA_NODE_ID: ${KAFKA_NODE_ID}
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_CONTROLLER_LISTENER_NAMES: ${KAFKA_CONTROLLER_LISTENER_NAMES}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LOG_DIRS: ${KAFKA_LOG_DIRS}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: ${KAFKA_AUTO_CREATE_TOPICS_ENABLE}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: ${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS}
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: ${KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS}
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_KRAFT_CLUSTER_ID}
      CLUSTER_ID: ${CLUSTER_ID}
    volumes:
      - ./db/kafka_data:/var/lib/kafka/data
    networks:
      - docker-network-dev

  minio:
    image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    container_name: minio
    restart: always
    command: server --console-address ":${MINIO_PORT_1}" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_PORT_1}:9001"
    env_file:
      - .env
    volumes:
      - ./db/minio_data:/data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${MINIO_PORT}/minio/health/live",
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - docker-network-dev

networks:
  docker-network-dev:
    driver: bridge
