version: "3.8"
services:
  postgres:
    image: postgres:14.8
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - docker-network-dev

  timescale-ha:
    image: timescale/timescaledb-ha:pg15-latest
    container_name: timescale-ha
    restart: always
    environment:
      POSTGRES_USER: ${TIMESCALE_HA_USER}
      POSTGRES_PASSWORD: ${TIMESCALE_HA_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${TIMESCALE_HA_PORT}:5432"
    volumes:
      - ./db/timescale-ha:/home/postgres/pgdata/data
    networks:
      - docker-network-dev

  timescale:
    image: timescale/timescaledb:latest-pg16
    container_name: timescale
    restart: always
    environment:
      POSTGRES_USER: ${TIMESCALE_USER}
      POSTGRES_PASSWORD: ${TIMESCALE_PASSWORD}
    env_file:
      - .env
    ports:
      - "${TIMESCALE_PORT}:5432"
    volumes:
      - ./db/timescale:/var/lib/postgresql/data
    networks:
      - docker-network-dev

  mysql:
    image: mysql:8.0.31
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - docker-network-dev

  redis:
    image: redis:6.0.16
    container_name: redis
    restart: always
    volumes:
      - ./db/redis:/var/lib/redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_PORT_1}:16379"
    networks:
      - docker-network-dev

  mongodb:
    image: mongo:7.0.6
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./db/mongodb:/data/db
    networks:
      - docker-network-dev

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    env_file:
      - .env
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_PORT_UI}:15672"
    volumes:
      - ./db/rabbitmq:/var/lib/rabbitmq/mnesia/
    networks:
      - docker-network-dev

  elasticsearch:
    image: bitnami/elasticsearch:8.5.3
    container_name: elasticsearch
    restart: always
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
      - "${ELASTICSEARCH_PORT_1}:9300"
    volumes:
      - ./db/elastic:/bitnami/elasticsearch/data
    networks:
      - docker-network-dev

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: kibana
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOST}
    env_file:
      - .env
    ports:
      - "${kIBANA_PORT}:5601"
    networks:
      - docker-network-dev

networks:
  docker-network-dev:
    driver: bridge
